FROM php:7.3-apache

# install the PHP extensions we need
RUN set -ex; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	apt-get install -y --no-install-recommends \
		libjpeg-dev \
		libpng-dev \
		libzip-dev \
        libmemcached-dev \
        zlib1g-dev \
        libmagickwand-dev \
	; \
	\
	docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
	docker-php-ext-install gd mysqli opcache zip bcmath exif; \
    docker-php-ext-enable exif; \
    docker-php-ext-enable bcmath; \
    pecl install memcached-3.1.3; \
    docker-php-ext-enable memcached; \
    pecl install imagick; \
    docker-php-ext-enable imagick; \
	\

# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark; \
	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
		| awk '/=>/ { print $3 }' \
		| sort -u \
		| xargs -r dpkg-query -S \
		| cut -d: -f1 \
		| sort -u \
		| xargs -rt apt-mark manual; \
	\
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    apt-get install -y git; \
	rm -rf /var/lib/apt/lists/*

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=2'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

# https://codex.wordpress.org/Editing_wp-config.php#Configure_Error_Logging
RUN { \
		echo 'error_reporting = 4339'; \
		echo 'display_errors = Off'; \
		echo 'display_startup_errors = Off'; \
		echo 'log_errors = On'; \
		echo 'error_log = /dev/stderr'; \
		echo 'log_errors_max_len = 1024'; \
		echo 'ignore_repeated_errors = On'; \
		echo 'ignore_repeated_source = Off'; \
		echo 'html_errors = Off'; \
	} > /usr/local/etc/php/conf.d/error-logging.ini

RUN a2enmod rewrite expires remoteip headers; \
    echo "RemoteIPHeader X-Forwarded-For" > /etc/apache2/conf-available/remoteip.conf; \
    a2enconf remoteip

RUN { \
        echo 'DefaultRuntimeDir ${APACHE_RUN_DIR}'; \
        echo 'PidFile ${APACHE_PID_FILE}'; \
        echo 'Timeout 90'; \
        echo 'KeepAlive On'; \
        echo 'MaxKeepAliveRequests 100'; \
        echo 'KeepAliveTimeout 5'; \
        echo 'User ${APACHE_RUN_USER}'; \
        echo 'Group ${APACHE_RUN_GROUP}'; \
        echo 'HostnameLookups Off'; \
        echo 'ErrorLog ${APACHE_LOG_DIR}/error.log'; \
        echo 'LogLevel warn'; \
        echo 'IncludeOptional mods-enabled/*.load'; \
        echo 'IncludeOptional mods-enabled/*.conf'; \
        echo 'Include ports.conf'; \
        echo '<Directory />'; \
        echo '        Options +FollowSymLinks -Indexes -Includes'; \
        echo '        AllowOverride None'; \
        echo '        Require all denied'; \
        echo '</Directory>'; \
        echo '<Directory /usr/share>'; \
        echo '        AllowOverride None'; \
        echo '        Require all granted'; \
        echo '</Directory>'; \
        echo '<Directory /var/www/>'; \
        echo '        Options -Indexes -Includes +FollowSymLinks'; \
        echo '        AllowOverride None'; \
        echo '        Require all granted'; \
        echo '</Directory>'; \
        echo 'AccessFileName .htaccess'; \
        echo '<FilesMatch "^\.ht">'; \
        echo '        Require all denied'; \
        echo '</FilesMatch>'; \
        echo 'IncludeOptional conf-enabled/*.conf'; \
        echo 'IncludeOptional sites-enabled/*.conf'; \
    } > /etc/apache2/apache2.conf

RUN { \
        echo '<VirtualHost *:80>'; \
        echo 'ServerAdmin webmaster@localhost'; \
        echo 'DocumentRoot /var/www/html'; \
        echo 'SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded'; \
        echo 'LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined'; \
        echo 'LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" forwarded'; \
        echo 'ErrorLog ${APACHE_LOG_DIR}/error.log'; \
        echo 'CustomLog ${APACHE_LOG_DIR}/access.log combined env=!forwarded'; \
        echo 'CustomLog ${APACHE_LOG_DIR}/access.log forwarded env=forwarded'; \
        echo '</VirtualHost>'; \
    } > /etc/apache2/sites-available/000-default.conf

RUN { \
        echo '### SECURITY HARDENING STARTS ###'; \
        echo 'TraceEnable off'; \
        echo 'FileETag None'; \
        echo 'ServerSignature Off'; \
        echo 'ServerTokens Prod'; \
        echo 'Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure'; \
        echo 'Header always append X-Frame-Options SAMEORIGIN'; \
        echo 'Header set X-XSS-Protection "1; mode=block"'; \
        echo '### SECURITY HARDENING ENDS ###'; \
    } >  /etc/apache2/conf-available/security.conf

RUN a2enconf security

COPY ./wordpress/ /var/www/html

RUN set -ex; \
    chown -R www-data:www-data /var/www/html; \
    chmod -R 0644 /var/www/html
RUN find /var/www/html -type d -exec chmod ug+x {} \;

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["apache2-foreground"]
